import Head from 'next/head'
import Image from 'next/image'
import Banner from '../components/Banner'
import Footer from '../components/Footer'
import Header from '../components/Header'
import LargeCard from '../components/LargeCard'
import MediumCard from '../components/MediumCard'
import SmallCard from '../components/SmallCard'

export default function Home({exploreData, cardData}) {
  return (
    <div className=''>
      <Head>
        <title>Airbnb Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      {/* {Header} */}

         <Header />
      <Banner />

      <main className='max-w-7xl  pb-44 px-8 sm:px-16 '>
        <section className='pt-6 '>
         <h2 className='font-semibold text-4xl pb-6'>Explore Nearby</h2>

        <div className='grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 
        xl:grid-cols-4 2xl:grid-cols-6'>
        {exploreData?.map(({img, location, distance}) =>
        
        <SmallCard  key={img} img={img} location={location} distance={distance}/>
         )}
        </div>
        </section>

        <section>
        <h2 className='text-4xl font-semibold py-8'>Live Anywhere</h2>
       <div className='
       flex overflow-scroll space-x-4 scrollbar-hide'>
       {cardData?.map(({img,title}) => (
                    <MediumCard key={img} img={img} title={title} />

        )
      )}
       </div>
        </section>

        <LargeCard img='https://a0.muscache.com/im/pictures/2da67c1c-0c61-4629-8798-1d4de1ac9291.jpg?im_w=1440'
        title="The Greatest Outdoor"
        description="WishList curated by Airbnb"
        buttonText="Inspired"/>
        
      </main>
      <Footer />
    </div>
  )
}

export async function getStaticProps() {
  const exploreData = await fetch('https://www.jsonkeeper.com/b/4G1G').then(
    res => res.json()
  )
  const cardData = await fetch('https://www.jsonkeeper.com/b/VHHT').then(
    res => res.json()
  )

  return {
    props: {
      exploreData,
      cardData
    }
  }

}